### ISSUE TITLE
java.io.IOException

### ISSUE THREAD

**Issue by EkEhsaas** [musically-ut/matlab-stanford-postagger#3]
I'm trying to use your files. But I'm receiving these errors:

```
Error using PosTaggerM (line 40)
Java exception occurred:
edu.stanford.nlp.io.RuntimeIOException: Unrecoverable error while loading a tagger model

	at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:758)

	at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:289)

	at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:253)

Caused by: java.io.IOException: Unable to resolve "./english-left3words-distsim.tagger" as either class path,
filename or URL

	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:434)

	at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:753)

	... 2 more
```

What I did: I added the folder of the file `english-left3words-distsim.tagger` in the path and added `stanford-postagger.jar ` to the classpath as you suggested [here](https://github.com/musically-ut/matlab-stanford-postagger). Then I used this code for testing:

```
sample_sentence = 'This is a very small sample sentence for test purpose - Chomsky.';
PosTaggerM(sample_sentence)
```

I have tried on both MATLAB R2014a and R2016a 64bit Win 10
I have tried with both 3.3.1 and 3.4.1 of the tagger and also tried some other versions.
Tried with latest java,  and also with Version 8 Update 73 (build 1.8.0_73-b02) and also with Java 1.7.0_60-b19.  .

How to solve this issue?

**Comment by musically-ut** [comment]
Moving `./english-left3words-distsim.tagger` to the current folder (`pwd`) doesn't help?

**Comment by EkEhsaas** [comment]
oh wow really! it worked.  really thankful. can you explain why it wasn't working before? I had added the path to its directory in MATLAB search path though! (I am not familiar with Java)

**Comment by musically-ut** [comment]
The `PATH` is only a variable which is taken into account for executables on the shell, i.e. if bash or CMD cannot find an executable with the name you have typed in the current folder, then it will continue looking for that executable in the locations given in the `PATH`.

However, other programs which are trying to load data files do not by default look into the locations shown in `PATH`; they only look in the relative or absolute location passed to them (in this case, a relative location `./`, which is the current directory). 

Hope that helps; good luck!

**Comment by EkEhsaas** [comment]
Thanks sir! as I understand it, shouldn't it work if I replace this line from your code:
`tagger = MaxentTagger('./english-left3words-distsim.tagger');`
to this:

`tagger = MaxentTagger('C:/Users/EkEhsaas/Desktop/stanford-postagger-full-2014-01-04/models/english-left3words-distsim.tagger');`

where `C:/Users/EkEhsaas/Desktop/stanford-postagger-full-2014-01-04/models/` is where the file is present but that is not current folder?

Doing the above gives me this:

```
Error using PosTaggerM (line 41)
Java exception occurred:
java.lang.IllegalArgumentException: name

	at sun.misc.URLClassPath$Loader.findResource(Unknown Source)

	at sun.misc.URLClassPath.findResource(Unknown Source)

	at java.net.URLClassLoader$2.run(Unknown Source)

	at java.net.URLClassLoader$2.run(Unknown Source)

	at java.security.AccessController.doPrivileged(Native Method)

	at java.net.URLClassLoader.findResource(Unknown Source)

	at java.lang.ClassLoader.getResource(Unknown Source)

	at java.lang.ClassLoader.getResource(Unknown Source)

	at java.net.URLClassLoader.getResourceAsStream(Unknown Source)

	at com.mathworks.jmi.CustomURLClassLoader.getResourceAsStream(ClassLoaderManager.java:796)

	at edu.stanford.nlp.io.IOUtils.findStreamInClasspathOrFileSystem(IOUtils.java:382)

	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:425)

	at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(MaxentTagger.java:753)

	at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:289)

	at edu.stanford.nlp.tagger.maxent.MaxentTagger.<init>(MaxentTagger.java:253)
```

**Comment by musically-ut** [comment]
From the looks of it, the file wasn't found at the given location. Windows generally uses `\` as the folder separator and not '/'. Try giving the path as `'C:\\Users\\EkEhsaas\\Desktop\\stanford-postagger-full-2014-01-04\\models\\english-left3words-distsim.tagger'` (note that the double `\\` are important).

**Comment by EkEhsaas** [comment]
Sir I tried your suggestion but it gave the same error

**Comment by musically-ut** [comment]
The problem seems to be with how absolute paths in Windows format are handled in `sun.misc.URLClassPath$Loader.findResource`, [same as this issue](https://github.com/spring-projects/spring-boot/issues/5650). You may need to give the complete relative path unfortunately.

**Comment by musically-ut** [comment]
The problem seems to be with how absolute paths in Windows format are handled in `sun.misc.URLClassPath$Loader.findResource`, [same as this issue](https://github.com/spring-projects/spring-boot/issues/5650). You may need to give the complete relative path unfortunately.

**Comment by EkEhsaas** [comment]
Thank you sir for your responses. I also want to verify that your code also works in MATLAB R2016a.

**Comment by EkEhsaas** [comment]
I have solved the problem of using absolute paths. I have found that adding `file:` solves the issue. Backslash and forward-slash both work. Two slashes and single slash both work.

Following are some examples that work for me:

```
tagger = MaxentTagger('file:\C:\Users\EkEhsaas\Desktop\stanford-postagger-full-2014-01-04\models\english-left3words-distsim.tagger');
```
```
tagger = MaxentTagger('file:C:\Users\EkEhsaas\Desktop\stanford-postagger-full-2014-01-04\models\english-left3words-distsim.tagger');
```

```
tagger = MaxentTagger('file:\\C:\\Users\\EkEhsaas\\Desktop\\stanford-postagger-full-2014-01-04\\models\\english-left3words-distsim.tagger');
```

```
tagger = MaxentTagger('file:C:/Users/EkEhsaas/Desktop/stanford-postagger-full-2014-01-04/models/english-left3words-distsim.tagger');
```

I also verify that your code also works in MATLAB R2016a.
Thank you again!

**Comment by musically-ut** [comment]
Thanks for posting the solution!

**Comment by musically-ut** [comment]
Could you also post what version of JRE/Tagger you used? I'll update the `README` with that information.

**Comment by EkEhsaas** [comment]
Java 1.7.0_60-b19
Tagger 3.4.1
