### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Sardar-Usama** [musically-ut/matlab-stanford-postagger#4]
I'm using your code. After spending some time to find the latest tagger that works with your code, I have the following conclusion to make:

The latest versions of MATLAB, Java and tagger as by now (20th July, 2017) that I have tried and found your code working are:  MATLAB R2017a, Java 8 Update 141, Stanford-Postagger 3.4.1.
 
I am attaching a list of my details for future reference.

##  Stanford-Postagger

I have found your code working with: 
- 3.3.0
- 3.3.1
- 3.4.1

The following versions don't work: 
- 3.5.0
- 3.5.1
- 3.5.2
- 3.7.0
- 3.8.0

All above non-working versions give this error:
```
Arguments to IMPORT must either end with ".*" or else specify a fully qualified
class name: "edu.stanford.nlp.tagger.maxent.MaxentTagger" fails this test.

```
I didn't dig into this but there may be a solution to above problem as well. What I have observed is that the version 3.5.0 and later versions which use Java 8 are not compatible with the code (as it is). The same issue was pointed out in [this thread](https://github.com/musically-ut/matlab-stanford-postagger/issues/2) with the version 3.7.0.

## Java version
It have tried it on the latest version as by now (20th July, 2017) i.e. Java 8 Update 141 (1.8.0_141-b15) (Release date July 18, 2017) and found it working.

## MATLAB version
It have tried it on the following versions:
R2016a (Windows)
R2017a (Windows)
Both work.

**Comment by musically-ut** [comment]
Thank you for the detailed analysis and the write-up!

**Comment by Sardar-Usama** [comment]
:) would you please correct these typos:

- Spelling of my name [here](https://github.com/musically-ut/matlab-stanford-postagger#acknowledgements)
- Java 1.8 is JRE 8 (not JRE 7). Typo [here](https://github.com/musically-ut/matlab-stanford-postagger#compatibility).
- Typo in the [last line of usage](https://github.com/musically-ut/matlab-stanford-postagger#usage).

Regards

**Comment by musically-ut** [comment]
Thanks again! I've fixed those typos.
